name: dash
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - dash
  - dash-ag-grid
  - fiona
  - folium
  - geocube
  - geopandas
  - h5netcdf
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - plotly
  - pyarrow
  - rasterio
  - rioxarray
  - setuptools<81
  - shapely
  - xarray
  - zarr
